### ISSUE TITLE
scale the display images to a proper size

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jinabox.js#11]
I've tried flowersearch example with jinabox. Currently, the images totally break the UI.

![image](https://user-images.githubusercontent.com/4329072/86784562-3ed41280-c094-11ea-8593-324b5efff303.png)
![image](https://user-images.githubusercontent.com/4329072/86784654-5a3f1d80-c094-11ea-80d3-9ead044b3131.png)

**Comment by imsergiy** [comment]
Addressed in commit 6fee5a7d9d62ac5222d1fc3c7e53b16c4e91a502
