### ISSUE TITLE
dropping text is not supported yet

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jinabox.js#12]
As a user, I would like to be able to select a large corpus of text and drop it into jinabox so that I don't need to copy and paste.

![image](https://user-images.githubusercontent.com/4329072/87001490-2aa22980-c1ea-11ea-9dfd-b9ed0a5b286b.png)

**Comment by imsergiy** [comment]
Added support for dropping text in df4be889a9f1e43062652acfa31f85a87d24a53b
