### ISSUE TITLE
UI: Drop zones not working on Firefox

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jinabox.js#4]
**Describe your problem**

In Firefox, drag and drop does not work. Dragging a Pokemon image from the left side doesn't cause drop zones to pop up, or causes the lower left one to pop up when mouse is not near it (closing the pop-up when the mouse gets closer)

Dropping the file leads to expected result (i.e. search results appearing)

**What is your guess?**
I guess it was coded for Chrome first and not tested on FF?

---

**Environment**

* Firefox 77.01 on Manjaro Linux
* Javascript enabled
* Server endpoint: http://localhost:65481/api/search
* Pokedex example

**Screenshots**
Can't capture a screenshot when dragging the mouse unfortunately

**Comment by imsergiy** [comment]
Fixed in commit 0ae47c24e3e1c917ff091db15a6763bed09a2d3b
