### ISSUE TITLE
UI: Server endpoint text displayed by default but not set

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jinabox.js#5]
**Describe your problem**
I tried for ages to get jinabox working with endpoint http://localhost:65481/api/search. I *thought* it was already set to that because that's already displayed in the server endpoint textbox, but turns out it's just placeholder text and not actually set.

This is really not obvious :/

**What is your guess?**
* Placeholder text is too dark. Lighten it to ensure it's clear that's placeholder
* Pop up an error if there is no server endpoint set, and highlight the server endpoint box in red

---

**Environment**
Firefox and Chrome on Manjaro

**Screenshots**
![Screenshot from 2020-06-19 15-27-38](https://user-images.githubusercontent.com/4182659/85093870-7b54e100-b241-11ea-85ec-c384593ddc4a.png)

**Comment by imsergiy** [comment]
Addressed placeholder style in commit e4cc470d371b0debf789789238cfa40f8f40b221
