### ISSUE TITLE
UI: Two dropzones is confusing

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jinabox.js#6]
**Describe your problem**
Dragging and dropping a Pokemon image (or anything else) results in two dropzones (search bar and action button on bottom left). This is a little confusing - where should I drop?

I mean, I know I can drop anywhere, but it's not clear to new users straight away. It'd be like your browser having two refresh buttons that both do same thing.

**Suggestion**

* Remove one drop zone or expand dropzone to whole area

---

**Environment**
Chrome on Linux (dropzones work inconsistently in Firefox, see #4)

**Screenshots**
No screenshot because it won't work while dragging

**Comment by imsergiy** [comment]
I added the ability for developers to toggle which components display dropzones in commit fc9fbc7a808bc78e8af7537478e920da544cccaa
