### ISSUE TITLE
Image upload from "browse" button does nothing

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jinabox.js#7]
**Describe your problem**
* Go to 'Upload' tab
* Browse for image, select image, click OK
* Nothing happens

**What is your guess?**

No idea. Dragging and dropping images from file folder works fine though

---

**Environment**
Chrome/Firefox on Manjaro Linux

**Screenshots**
Since nothing happens, nothing to screenshot

**Comment by imsergiy** [comment]
Addressed in commit e27e8f85320bb499762b4cfab2d728a5ebef0dac
